version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - './:/src'
    networks:
      - app-network

  nginx:
    image: 'nginx:alpine'
    container_name: reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificates/nginx-selfsigned.crt:/etc/nginx/certificates/nginx-selfsigned.crt
      - ./certificates/nginx-selfsigned.key:/etc/nginx/certificates/nginx-selfsigned.key
      - ./certificates/dhparam.pem:/etc/nginx/dhparam.pem
      - ./certificates/ssl-params.conf:/etc/nginx/certificates/ssl-params.conf
    ports:
        - '80:80'
        - '443:443'
    depends_on:
      - backend
    networks:
      - app-network

  # Database service used for development
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456789

networks:
  app-network:
    driver: bridge